name: Sentiment Stock Correlation CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pandas matplotlib seaborn textblob
          python -m textblob.download_corpora

      - name: Run main script
        run: python main.py  # change if your script file is named differently

      - name: Show Python version
        run: python --version
